### PR TITLE
Editorial improvements noted during IESG Evaluation

### PR DESCRIPTION
**Pull request by kaduk**

### CODE REVIEW

**Comment by paulehoffman** [comment]
All these changes look fine to me. After accepting them, I'll make a minor fix, but I didn't want to fight with git over it.

**Comment by cabo** [comment]
Thank you for this pull request!
We are closing it now as we cherry-picked most of the changes, possibly after applying some more editing to them, into d389699 and 9bf0a31.  Exceptions are:

* We did not pick the change from "Undefined" to "Undefined value", as this would have been confusing under "Expressio Unius Est Exclusio Alterius" (when one or more things of a class are expressly mentioned others of the same class are excluded -- Merriam-Webster) -- for consistency, we would have had to add the word "value" to False, True, Null, and probaby a few more places if we had added it to Undefined.
* We did not complete picking the change yet that removed the word "half-precision" -- we don't want to entirely remove this guidance, but we need to work on phrasing this more accessibly.  This is on our todo list for an upcoming PR.

**Comment by kaduk** [comment]
> We did not pick the change from "Undefined" to "Undefined value"

This was proposed because Table 4 and Table 7 use a different formulation; perhaps Table 4 could be adjusted instead, then?

**Comment by cabo** [comment]
Good point!  Now fixed in Table 4, 4b90a6b instead.

**Pull request closed without merging**
