### PR TITLE
Clarify that `undefined` is optional.

### PR DESCRIPTION
**Pull request by jyasskin**

### CODE REVIEW

**Comment by cabo** [comment]
While this change tells the reader that what was said was not a mistake, that is something the reader should assume for an RFC anyway. I believe that addition distracts more than it clarifies.

**Comment by cabo** [comment]
(And we probably need a discussion of what we mean when we say "optional" -- every kind of data item is "optional" in CBOR because the specific data model might not need it.  We might want to add a whole subsection about generic encoders and decoders, but this would really be BCP material and not something for the standard.)

**Comment by jyasskin** [comment]
I've read too many mistakes in standards to assume that for RFCs, and especially not for drafts on their way through the RFC process, but I don't think this is an essential change either.

**Comment by paulehoffman** [comment]
I think that the addition of the note about "undefined" is reasonable and not distracting. It should be accepted for a future version of the draft.

**Pull request merged**
